/** @type {import('next').NextConfig} */
const nextConfig = {
  trailingSlash: false,
  images: {
    loader: 'custom',
    loaderFile: './src/lib/cloudinary.ts',
    // Cap srcSet at 1920 -- no container on the site is wider than this.
    // Saves unnecessary downloads of 2048w/3840w images.
    deviceSizes: [640, 750, 828, 1080, 1200, 1440, 1920],
    imageSizes: [16, 32, 64, 96, 128, 256, 384],
  },
  async redirects() {
    return [
      // === SERVICE PAGES (redirect to training category pages) ===
      { source: '/services/utility-avoidance', destination: '/training/cable-location-avoidance', permanent: true },
      { source: '/services/utility-mapping', destination: '/training/utility-mapping-surveying', permanent: true },
      { source: '/services/osca', destination: '/osca', permanent: true },
      { source: '/services/utility-mapping/borehole-surveys', destination: '/contact', permanent: true },
      { source: '/services/utility-avoidance/cat-scanning', destination: '/training/cable-location-avoidance', permanent: true },
      { source: '/services/utility-avoidance/gpr', destination: '/courses/gpr-training', permanent: true },
      { source: '/services/utility-avoidance/potholing', destination: '/contact', permanent: true },
      { source: '/services/utility-mapping/mala-gpr', destination: '/courses/gpr-training', permanent: true },
      { source: '/services/utility-mapping/record-searches', destination: '/contact', permanent: true },
      { source: '/services/osca/training', destination: '/osca', permanent: true },
      { source: '/services/osca/certification', destination: '/osca', permanent: true },
      // Catch-all for any remaining /services/* paths
      { source: '/services/:path*', destination: '/courses', permanent: true },
      // === FOOTER/LEGACY LINK REDIRECTS ===
      { source: '/privacy', destination: '/privacy-policy', permanent: true },
      { source: '/blog', destination: '/knowledge-hub', permanent: true },
      { source: '/sitemap.htm', destination: '/courses', permanent: true },
      { source: '/observer.php', destination: '/knowledge-hub', permanent: true },
      { source: '/training', destination: '/courses', permanent: true },
      { source: '/certification', destination: '/accreditations', permanent: true },
      { source: '/case-studies', destination: '/knowledge-hub', permanent: true },
      // === KNOWLEDGE HUB CLIENT-SIDE REDIRECT (from Lovable Navigate) ===
      { source: '/knowledge-hub/npors-vs-eusr-cable-avoidance', destination: '/knowledge-hub/npors-vs-eusr', permanent: true },
      { source: '/knowledge-hub/cable-strikes', destination: '/knowledge-hub', permanent: true },
      { source: '/knowledge-hub/training', destination: '/knowledge-hub', permanent: true },
      { source: '/knowledge-hub/standards', destination: '/knowledge-hub/hsg47-explained', permanent: true },
      // === OLD SITE COURSE PAGES ===
      { source: '/courses/cat-genny-training', destination: '/courses/cat-and-genny-training', permanent: true },
      { source: '/courses/genny-cat-training', destination: '/courses/cat-and-genny-training', permanent: true },
      { source: '/courses/rd8000-training-courses', destination: '/courses/manufacturer-locator-training', permanent: true },
      { source: '/courses/vivax-training', destination: '/courses/vscan-and-transmitter-training', permanent: true },
      { source: '/courses/pas128-utility-surveyor-training', destination: '/courses/5-day-pas128-surveyor', permanent: true },
      { source: '/courses/gps-introduction-to-total-station', destination: '/courses/tsa-ices-utility-mapping', permanent: true },
      // MALA GPR
      { source: '/mala-gpr/core', destination: '/courses/gpr-training', permanent: true },
      { source: '/mala-gpr/hdr', destination: '/courses/gpr-training', permanent: true },
      { source: '/mala-gpr/hdr-pro', destination: '/courses/gpr-training', permanent: true },
      { source: '/mala-gpr/hdr-wideband', destination: '/courses/gpr-training', permanent: true },
      { source: '/mala-gpr/gpr-hire', destination: '/contact', permanent: true },
      { source: '/mala-gpr/service-calibration', destination: '/contact', permanent: true },
      { source: '/mala-gpr', destination: '/courses/gpr-training', permanent: true },
      // Old site pages
      { source: '/forms', destination: '/contact', permanent: true },
      { source: '/downloads', destination: '/knowledge-hub', permanent: true },
      { source: '/courses-availability', destination: '/contact', permanent: true },
      { source: '/courses/vscan-training', destination: '/courses/cat-and-genny-training', permanent: true },
      // EUS -> EUSR slug migration (2026-04-22): URL slugs corrected to match content which already says EUSR
      { source: '/courses/eus-cat1', destination: '/courses/eusr-cat1', permanent: true },
      { source: '/courses/eus-cat2-safe-dig', destination: '/courses/eusr-cat2-safe-dig', permanent: true },
      { source: '/courses/eus-superuser', destination: '/courses/eusr-superuser', permanent: true },
      { source: '/courses/eus-cat1-cat2-combined', destination: '/courses/eusr-cat1-cat2-combined', permanent: true },
      { source: '/courses/eus-cat1-cat2-usc-combined', destination: '/courses/eusr-cat1-cat2-usc-combined', permanent: true },
      { source: '/knowledge-hub/eus-cat1-vs-proqual-cat1', destination: '/knowledge-hub/eusr-cat1-vs-proqual-cat1', permanent: true },
      { source: '/courses/eus-1-cat-genny', destination: '/courses/eusr-cat1', permanent: true },
      { source: '/courses/online-live-cat-genny', destination: '/courses/cat-and-genny-training', permanent: true },
      { source: '/courses/online-live-cat-genny-training', destination: '/courses/cat-and-genny-training', permanent: true },
      { source: '/courses/online-cat4-data', destination: '/courses/cat4-hsg47-awareness-online', permanent: true },
      { source: '/courses/online-cat4-data-course', destination: '/courses/cat4-hsg47-awareness-online', permanent: true },
      { source: '/courses/zsi-super-user', destination: '/courses/zs-superuser-scottish-water', permanent: true },
      { source: '/courses/zsi-super-user-locator-training', destination: '/courses/zs-superuser-scottish-water', permanent: true },
      { source: '/courses/ground-penetrating-radar', destination: '/courses/gpr-training', permanent: true },
      { source: '/courses/rqf-qcf-level-2', destination: '/courses/rqf-level-2-award', permanent: true },
      { source: '/courses/qcf-level-2', destination: '/courses/rqf-level-2-award', permanent: true },
      { source: '/courses/online-utility-mapping', destination: '/courses/online-level-3-diploma', permanent: true },
      { source: '/courses/online-utility-mapping-training', destination: '/courses/online-level-3-diploma', permanent: true },
      { source: '/courses/qcf-level-3', destination: '/courses/level-3-certificate', permanent: true },
      { source: '/courses/qcf-level-3-utility-mapping', destination: '/courses/level-3-certificate', permanent: true },
      { source: '/courses/qcf-level-3-utility-surveyor-qualification', destination: '/courses/level-3-certificate', permanent: true },
      { source: '/courses/qcf-level-5', destination: '/courses/level-5-diploma', permanent: true },
      { source: '/courses/qcf-level-5-utility-mapping', destination: '/courses/level-5-diploma', permanent: true },
      { source: '/courses/mala-gpr-training', destination: '/courses/gpr-training', permanent: true },
      // Legacy blog/article URLs
      { source: '/radiodetection-cat-4-and-genny-4-training', destination: '/courses/cat-and-genny-training', permanent: true },
      { source: '/pas-128-surveyor', destination: '/courses/5-day-pas128-surveyor', permanent: true },
      { source: '/why-having-a-permit-doesnt-mean-youre-hsg47-compliant', destination: '/knowledge-hub/hsg47-explained', permanent: true },
      { source: '/hsg47-is-a-guide-issued-by-the-hse-for-those-involved-in-any-sort-of-excavation', destination: '/knowledge-hub/hsg47-explained', permanent: true },
      { source: '/how-do-cable-locators-work-key-principles-of-buried-utility-detection', destination: '/knowledge-hub', permanent: true },
      // Internal restructuring
      { source: '/bespoke-training/design-your-programme', destination: '/bespoke-training', permanent: true },
      { source: '/design-your-programme', destination: '/bespoke-training', permanent: true },
      { source: '/designyourprogramme', destination: '/bespoke-training', permanent: true },
      { source: '/courses/utility-avoidance', destination: '/training/cable-location-avoidance', permanent: true },
      { source: '/courses/proqualcat1', destination: '/courses/proqualcat1-training', permanent: true },
      { source: '/courses/proqual-level-3-cat-and-genny', destination: '/courses/proqualcat1-training', permanent: true },
      { source: '/courses/utility-mapping', destination: '/training/utility-mapping-surveying', permanent: true },
      { source: '/courses/proqualevel2', destination: '/courses/rqf-level-2-award', permanent: true },
      { source: '/courses/prqual-cat1-cable-avoidance', destination: '/courses/proqualcat1-training', permanent: true },
      { source: '/courses/mala-hdr-pro', destination: '/training/utility-mapping-surveying', permanent: true },
      { source: '/courses/mala-gpr-service-calibration', destination: '/courses/gpr-training', permanent: true },
      // WordPress blog posts Session 33
      { source: '/when-using-cable-avoidance-tools-you-need-to-understand-their-limitations', destination: '/knowledge-hub', permanent: true },
      { source: '/what-is-the-right-cable-avoidance-tool-cat-for-your-needs', destination: '/knowledge-hub', permanent: true },
      { source: '/expert-qa-get-your-cat-genny-questions-answered', destination: '/courses/cat-and-genny-training', permanent: true },
      { source: '/if-undertaking-excavation-work-it-is-best-practice-to-use-line-search-before-u-dig', destination: '/knowledge-hub', permanent: true },
      { source: '/cat-genny-training-what-is-it-what-it-involves', destination: '/courses/cat-and-genny-training', permanent: true },
      { source: '/a-step-by-step-guide-for-aspiring-utility-surveyors-in-the-uk', destination: '/knowledge-hub', permanent: true },
      { source: '/how-cat-and-genny-training-enhances-site-safety', destination: '/courses/cat-and-genny-training', permanent: true },
      { source: '/locating-underground-services-is-essential-before-any-excavation', destination: '/knowledge-hub', permanent: true },
      { source: '/cutting-the-cord-a-beginners-guide-to-cable-avoidance', destination: '/training/cable-location-avoidance', permanent: true },
      { source: '/cat-and-genny-training-the-basics', destination: '/courses/cat-and-genny-training', permanent: true },
      { source: '/how-does-the-radiodetection-rd8100-tool-work', destination: '/courses/manufacturer-locator-training', permanent: true },
      { source: '/understanding-the-radiodetection-rd8100-a-guide-to-utility-locating', destination: '/courses/manufacturer-locator-training', permanent: true },
      { source: '/it-is-essential-to-carry-out-a-survey-before-undertaking-any-excavation', destination: '/knowledge-hub', permanent: true },
      { source: '/before-digging-on-a-construction-project-it-is-essential-to-carry-out-a-survey', destination: '/knowledge-hub', permanent: true },
      { source: '/locating-underground-services-what-you-need-to-know', destination: '/knowledge-hub', permanent: true },
      { source: '/excavation-safety-a-crash-course', destination: '/knowledge-hub', permanent: true },
      { source: '/how-to-choose-the-right-cable-avoidance-tool', destination: '/training/cable-location-avoidance', permanent: true },
      { source: '/how-to-reduce-the-risks-of-cable-avoidance', destination: '/training/cable-location-avoidance', permanent: true },
      { source: '/cable-avoidance-101-a-beginners-guide-to-safe-digging', destination: '/training/cable-location-avoidance', permanent: true },
      { source: '/news', destination: '/knowledge-hub', permanent: true },
      // HSG47 blog posts
      { source: '/hsg47-training-safely-detect-and-avoid-underground-services', destination: '/knowledge-hub/hsg47-explained', permanent: true },
      { source: '/hsg47-what-you-need-to-know-about-excavations', destination: '/knowledge-hub/hsg47-explained', permanent: true },
      { source: '/hsg47-course-practical-skills-for-underground-safety', destination: '/knowledge-hub/hsg47-explained', permanent: true },
      { source: '/do-you-need-eusr-hsg47', destination: '/knowledge-hub/hsg47-explained', permanent: true },
      { source: '/hsg47-training-whats-it-all-about', destination: '/knowledge-hub/hsg47-explained', permanent: true },
      { source: '/integrating-hsg47-training-with-pas-128-standards', destination: '/knowledge-hub/hsg47-explained', permanent: true },
      { source: '/overcoming-challenges-in-hsg47-training', destination: '/knowledge-hub/hsg47-explained', permanent: true },
      { source: '/why-hsg47-training-is-your-secret-weapon-for-safer-utility-work', destination: '/knowledge-hub/hsg47-explained', permanent: true },
      { source: '/hsg47-and-the-rise-of-mixed-utility-corridors-why-your-old-work-habits-dont-apply', destination: '/knowledge-hub/hsg47-explained', permanent: true },
      { source: '/understanding-the-hsg47-utility-mapping-certification-process', destination: '/knowledge-hub/hsg47-explained', permanent: true },
      { source: '/get-cable-avoidance-and-hsg47-training-by-sygma-solutions', destination: '/knowledge-hub/hsg47-explained', permanent: true },
      { source: '/eusr-hsg47-training-from-sygma-solutions', destination: '/knowledge-hub/hsg47-explained', permanent: true },
      { source: '/hsg47-and-remote-utility-detection-shaping-the-digital-age-practice', destination: '/knowledge-hub/hsg47-explained', permanent: true },
      { source: '/our-cable-avoidance-courses-follow-the-guidance-of-hsg47-training', destination: '/knowledge-hub/hsg47-explained', permanent: true },
      { source: '/eusr-hsg47-essentials-every-utility-worker-needs-to-know', destination: '/knowledge-hub/hsg47-explained', permanent: true },
      { source: '/operatives-who-need-to-locate-underground-services-need-hsg47-training', destination: '/knowledge-hub/hsg47-explained', permanent: true },
      { source: '/what-are-the-pressing-questions-about-hsg47', destination: '/knowledge-hub/hsg47-explained', permanent: true },
      { source: '/understanding-hsg-47-an-overview', destination: '/knowledge-hub/hsg47-explained', permanent: true },
      { source: '/our-hsg47-training-teaches-you-everything-you-need-to-know', destination: '/knowledge-hub/hsg47-explained', permanent: true },
      { source: '/the-hsg47-certification-you-should-not-ignore-protect-yourselves', destination: '/knowledge-hub/hsg47-explained', permanent: true },
      { source: '/the-hidden-costs-of-skipping-hsg47-training-real-world-lessons-from-cable-strikes', destination: '/knowledge-hub/hsg47-explained', permanent: true },
      { source: '/advice-from-the-hse-on-avoiding-dangers-from-excavation-works', destination: '/knowledge-hub/hsg47-explained', permanent: true },
      { source: '/understanding-hsg-47-a-guide-for-utility-detection-professionals', destination: '/knowledge-hub/hsg47-explained', permanent: true },
      // EUSR posts
      { source: '/eusr-cat-and-genny-training-from-sygma-solutions', destination: '/courses/eusr-cat1', permanent: true },
      { source: '/eusr-certification-your-guide-to-utility-safety-training', destination: '/courses/eusr-cat1', permanent: true },
      { source: '/eusr-cat-and-genny-training-that-sets-utility-pros-apart', destination: '/courses/eusr-cat1', permanent: true },
      { source: '/eusr-utility-location-training-cat-genny', destination: '/courses/eusr-cat1', permanent: true },
      { source: '/why-is-eusr-the-best-training-program-for-cable-avoidance', destination: '/courses/eusr-cat1', permanent: true },
      { source: '/understanding-the-eusr-certification-process-for-cat-and-genny-operators', destination: '/courses/eusr-cat1', permanent: true },
      { source: '/repeated-near-misses-on-uk-sites-and-what-eusr-training-would-have-caught-earlier', destination: '/courses/eusr-cat1', permanent: true },
      { source: '/stay-compliant-safe-cat-genny-certification-explained', destination: '/courses/eusr-cat1', permanent: true },
      // Utility mapping posts
      { source: '/our-utility-mapping-course-teaches-everything-you-need-to-know', destination: '/training/utility-mapping-surveying', permanent: true },
      { source: '/to-become-a-utility-surveyor-you-need-top-class-training', destination: '/training/utility-mapping-surveying', permanent: true },
      { source: '/utility-mapping-101-understanding-the-basics', destination: '/training/utility-mapping-surveying', permanent: true },
      { source: '/digging-smart-why-utility-mapping-training-is-essential', destination: '/training/utility-mapping-surveying', permanent: true },
      { source: '/utility-mapping-isnt-optional-anymore-heres-why', destination: '/training/utility-mapping-surveying', permanent: true },
      { source: '/what-is-cscs-utility-mapping', destination: '/training/utility-mapping-surveying', permanent: true },
      { source: '/everything-that-you-need-to-know-to-apply-for-a-cscs-utility-surveyor-card', destination: '/training/utility-mapping-surveying', permanent: true },
      { source: '/our-underground-surveyor-courses-teach-everything-you-need-to-know', destination: '/training/utility-mapping-surveying', permanent: true },
      { source: '/utility-coding-explained-a-sygma-solutions-guide', destination: '/training/utility-mapping-surveying', permanent: true },
      { source: '/utility-location-training-hands-on-real-world-skills', destination: '/training/utility-mapping-surveying', permanent: true },
      { source: '/new-utility-mapping-training-online', destination: '/training/utility-mapping-surveying', permanent: true },
      { source: '/understanding-the-red-lines-a-beginners-guide-to-reading-utility-stats-plans', destination: '/training/utility-mapping-surveying', permanent: true },
      { source: '/the-proqual-level-2-award-in-utility-avoidance', destination: '/courses/rqf-level-2-award', permanent: true },
      { source: '/level-5-qcf-diploma-senior-utilities-mapping-surveyor-qualification', destination: '/training/utility-mapping-surveying', permanent: true },
      { source: '/achieve-your-level-5-qcf-diploma-senior-utilities-surveyor-qualification', destination: '/training/utility-mapping-surveying', permanent: true },
      { source: '/what-you-need-to-know-in-order-to-become-a-level-5-utility-surveyor', destination: '/training/utility-mapping-surveying', permanent: true },
      { source: '/proqual-qcf-level-3-utility-surveyor-training-is-now-available-online', destination: '/training/utility-mapping-surveying', permanent: true },
      // GPR posts
      { source: '/ground-penetrating-radar-gpr-training', destination: '/courses/gpr-training', permanent: true },
      { source: '/what-you-need-to-know-about-gpr-locators', destination: '/courses/gpr-training', permanent: true },
      { source: '/mala-easy-locator-gets-easier-to-hire', destination: '/courses/gpr-training', permanent: true },
      { source: '/we-are-the-sole-uk-distributor-for-the-mala-easy-locator-hdr', destination: '/courses/gpr-training', permanent: true },
      { source: '/sygma-solutions-can-provide-you-with-mala-easy-locator-gpr-machines', destination: '/courses/gpr-training', permanent: true },
      { source: '/2013-december-free-mala-course-a-huge-success', destination: '/courses/gpr-training', permanent: true },
      // RD8100 posts
      { source: '/what-you-need-to-know-about-the-use-of-the-rd8100-cable-locator', destination: '/courses/manufacturer-locator-training', permanent: true },
      { source: '/training-in-the-use-of-the-rd8100-from-sygma-solutions', destination: '/courses/manufacturer-locator-training', permanent: true },
      { source: '/what-utility-strikes-reveal-about-teams-that-havent-had-radiodetection-training', destination: '/courses/manufacturer-locator-training', permanent: true },
      { source: '/the-key-to-utility-detection-radiodetection-training-that-works', destination: '/courses/manufacturer-locator-training', permanent: true },
      { source: '/vscan-training', destination: '/courses/vscan-and-transmitter-training', permanent: true },
      { source: '/vscan-training-from-sygma-solutions', destination: '/courses/vscan-and-transmitter-training', permanent: true },
      { source: '/sygma-solutions-can-provide-training-in-the-use-of-the-c-scope-tools', destination: '/courses/manufacturer-locator-training', permanent: true },
      // CAT & Genny posts
      { source: '/cat-4-and-genny-4-training-from-sygma-solutions', destination: '/courses/cat-and-genny-training', permanent: true },
      { source: '/an-overview-of-the-sygma-solutions-cat-and-genny-course', destination: '/courses/cat-and-genny-training', permanent: true },
      { source: '/who-needs-cat-genny-training-and-what-can-they-learn', destination: '/courses/cat-and-genny-training', permanent: true },
      { source: '/reasons-for-using-the-cat-genny-for-location-of-buried-services', destination: '/courses/cat-and-genny-training', permanent: true },
      { source: '/learn-the-basics-of-cat-and-genny-training-online', destination: '/courses/cat-and-genny-training', permanent: true },
      { source: '/cat-and-genny-training-from-sygma-solutions', destination: '/courses/cat-and-genny-training', permanent: true },
      { source: '/thorough-training-is-needed-in-order-to-fully-understand-the-cat-and-genny', destination: '/courses/cat-and-genny-training', permanent: true },
      { source: '/the-cat-and-genny-are-great-tools-but-have-certain-limitations', destination: '/courses/cat-and-genny-training', permanent: true },
      { source: '/cat-and-genny-training-is-vital-for-the-location-of-underground-services', destination: '/courses/cat-and-genny-training', permanent: true },
      { source: '/sygma-solutions-cat-and-genny-training-for-safer-operations', destination: '/courses/cat-and-genny-training', permanent: true },
      { source: '/sygma-solutions-leading-the-way-in-cat-and-genny-training', destination: '/courses/cat-and-genny-training', permanent: true },
      { source: '/why-sygma-solutions-cat-and-genny-training-is-critical-knowledge', destination: '/courses/cat-and-genny-training', permanent: true },
      { source: '/maximising-the-potential-of-cat-and-genny-tools', destination: '/courses/cat-and-genny-training', permanent: true },
      { source: '/maintaining-the-accuracy-of-your-cat-and-genny-gear', destination: '/courses/cat-and-genny-training', permanent: true },
      { source: '/who-needs-cat-and-genny-training-guide-for-utility-professionals', destination: '/courses/cat-and-genny-training', permanent: true },
      { source: '/choosing-the-right-cat-and-genny-mode-for-every-job', destination: '/courses/cat-and-genny-training', permanent: true },
      { source: '/online-cat-genny-training-prevent-costly-utility-strikes', destination: '/courses/cat-and-genny-training', permanent: true },
      { source: '/new-online-live-cat-genny-training', destination: '/courses/cat-and-genny-training', permanent: true },
      { source: '/hidden-wins-of-the-cat-genny-course-no-one-talks-about', destination: '/courses/cat-and-genny-training', permanent: true },
      { source: '/how-weather-ground-type-and-site-conditions-distort-cat-genny-performance', destination: '/courses/cat-and-genny-training', permanent: true },
      { source: '/navigating-high-frequency-signal-noise-in-urban-locating', destination: '/courses/cat-and-genny-training', permanent: true },
      { source: '/why-your-cat-data-is-the-new-site-blueprint', destination: '/courses/cat-and-genny-training', permanent: true },
      { source: '/the-data-trail-in-2026-why-your-cat4-memory-log-is-now-a-legal-requirement', destination: '/courses/cat-and-genny-training', permanent: true },
      { source: '/the-quiet-line-challenge-locating-abandoned-or-non-live-utilities', destination: '/courses/cat-and-genny-training', permanent: true },
      { source: '/why-higher-isnt-always-better-in-2026-urban-locating', destination: '/courses/cat-and-genny-training', permanent: true },
      { source: '/advanced-techniques-for-identifying-ghost-signals-in-cable-avoidance', destination: '/courses/cat-and-genny-training', permanent: true },
      // General cable avoidance posts
      { source: '/cable-avoidance-training-is-critical-for-contractors-undertaking-groundwork', destination: '/training/cable-location-avoidance', permanent: true },
      { source: '/cable-avoidance-training-for-safe-digging-and-excavation-work', destination: '/training/cable-location-avoidance', permanent: true },
      { source: '/our-training-will-enable-a-qualification-in-cable-avoidance', destination: '/training/cable-location-avoidance', permanent: true },
      { source: '/reduce-risk-stay-compliant-with-online-cable-avoidance-training', destination: '/training/cable-location-avoidance', permanent: true },
      { source: '/cable-avoidance-training-is-essential-for-those-who-need-to-locate-buried-services', destination: '/training/cable-location-avoidance', permanent: true },
      { source: '/cable-avoidance-training-from-sygma-solutions', destination: '/training/cable-location-avoidance', permanent: true },
      { source: '/cable-avoidance-training-is-essential-if-you-need-to-locate-underground-services', destination: '/training/cable-location-avoidance', permanent: true },
      { source: '/enroll-in-cable-avoidance-training-to-prevent-utility-strikes', destination: '/training/cable-location-avoidance', permanent: true },
      { source: '/5-things-learn-in-your-cable-avoidance-training-course', destination: '/training/cable-location-avoidance', permanent: true },
      { source: '/cable-strike-avoidance-training-from-sygma-solutions', destination: '/training/cable-location-avoidance', permanent: true },
      { source: '/master-cable-avoidance-with-sygmas-expert-training', destination: '/training/cable-location-avoidance', permanent: true },
      { source: '/what-most-people-miss-about-cable-avoidance-training', destination: '/training/cable-location-avoidance', permanent: true },
      { source: '/role-of-cat-training-in-preventing-cable-strikes', destination: '/training/cable-location-avoidance', permanent: true },
      { source: '/why-practical-experience-matters-more-than-manuals-in-cable-avoidance-training', destination: '/training/cable-location-avoidance', permanent: true },
      { source: '/the-evolution-of-cable-avoidance-tools', destination: '/training/cable-location-avoidance', permanent: true },
      { source: '/cable-avoidance-training-advice', destination: '/training/cable-location-avoidance', permanent: true },
      { source: '/common-challenges-in-cable-avoidance', destination: '/training/cable-location-avoidance', permanent: true },
      { source: '/strategies-and-best-practices-for-cable-avoidance', destination: '/training/cable-location-avoidance', permanent: true },
      { source: '/some-things-to-consider-when-investing-in-cable-avoidance-tools', destination: '/training/cable-location-avoidance', permanent: true },
      { source: '/why-accurate-cable-location-is-the-first-step-to-a-safe-worksite', destination: '/training/cable-location-avoidance', permanent: true },
      { source: '/our-cable-avoidance-training-covers-the-limitations-of-the-equipment-used', destination: '/training/cable-location-avoidance', permanent: true },
      { source: '/dont-guess-detect-why-cable-avoidance-training-matters', destination: '/training/cable-location-avoidance', permanent: true },
      { source: '/protect-lives-and-careers-with-cable-avoidance-skills', destination: '/training/cable-location-avoidance', permanent: true },
      { source: '/pros-and-cons-of-a-career-in-cable-avoidance', destination: '/training/cable-location-avoidance', permanent: true },
      { source: '/how-to-achieve-success-with-cable-avoidance', destination: '/training/cable-location-avoidance', permanent: true },
      { source: '/why-you-need-to-undertake-a-utility-avoidance-training-course', destination: '/training/cable-location-avoidance', permanent: true },
      { source: '/important-rules-to-follow-for-cable-avoidance', destination: '/training/cable-location-avoidance', permanent: true },
      { source: '/learn-to-safely-use-cat-and-genny-tools-for-excavation-projects', destination: '/training/cable-location-avoidance', permanent: true },
      { source: '/where-can-i-find-the-best-cable-avoidance-tools', destination: '/training/cable-location-avoidance', permanent: true },
      { source: '/catscan-training-for-cable-avoidance-is-critical', destination: '/training/cable-location-avoidance', permanent: true },
      { source: '/troubleshooting-common-issues-with-cat-tools', destination: '/training/cable-location-avoidance', permanent: true },
      { source: '/sygma-solutions-is-the-leading-cable-avoidance-training-company-in-the-uk', destination: '/', permanent: true },
      { source: '/the-foremost-uk-provider-of-training-for-the-location-of-underground-services', destination: '/', permanent: true },
      { source: '/sygma-solutions-specialists-in-the-training-of-underground-services-location', destination: '/', permanent: true },
      { source: '/some-of-the-things-you-will-learn-on-sygma-solutions-training-courses', destination: '/', permanent: true },
      { source: '/our-courses-are-perfect-to-enable-you-to-gain-the-qualifications-you-need', destination: '/', permanent: true },
      { source: '/our-traditional-courses-now-available-online', destination: '/', permanent: true },
      { source: '/2013-november-sygma-solutions-ltd-relocates', destination: '/', permanent: true },
      { source: '/2018-public-cat-and-genny-training', destination: '/', permanent: true },
      // General strike/safety posts
      { source: '/far-too-many-contractors-are-failing-to-check-for-cables-before-excavating', destination: '/knowledge-hub', permanent: true },
      { source: '/striking-an-underground-utility-can-be-life-threatening', destination: '/knowledge-hub', permanent: true },
      { source: '/shocking-statistics-concerning-safety-when-carrying-out-excavations', destination: '/knowledge-hub', permanent: true },
      { source: '/striking-underground-services-when-digging-can-be-fatal', destination: '/knowledge-hub', permanent: true },
      { source: '/stop-strikes-before-they-start-with-utility-detection', destination: '/knowledge-hub', permanent: true },
      { source: '/five-warning-signs-youre-about-to-hit-a-cable-and-how-to-avoid-it', destination: '/knowledge-hub', permanent: true },
      { source: '/what-is-excavation-safety', destination: '/knowledge-hub', permanent: true },
      { source: '/health-safety-in-the-construction-industry', destination: '/knowledge-hub', permanent: true },
      { source: '/it-is-always-necessary-to-obtain-plans-from-utilities-before-doing-any-form-of-excavation', destination: '/knowledge-hub', permanent: true },
      { source: '/why-a-site-survey-is-essential-before-carrying-out-any-excavation-work', destination: '/knowledge-hub', permanent: true },
      { source: '/underground-services-can-be-anywhere-even-in-places-you-might-not-expect', destination: '/knowledge-hub', permanent: true },
      { source: '/underground-services-can-literally-be-anywhere', destination: '/knowledge-hub', permanent: true },
      { source: '/the-multiple-issues-surrounding-location-of-underground-services', destination: '/knowledge-hub', permanent: true },
      { source: '/any-kind-of-excavation-work-can-be-dangerous', destination: '/knowledge-hub', permanent: true },
      { source: '/training-in-the-avoidance-of-underground-services-is-essential', destination: '/knowledge-hub', permanent: true },
      { source: '/training-in-the-use-of-tools-for-detecting-underground-services-is-essential', destination: '/knowledge-hub', permanent: true },
      { source: '/the-importance-of-training-for-utility-detection-equipment-and-surveying', destination: '/knowledge-hub', permanent: true },
      { source: '/do-you-know-exactly-where-the-electricity-cable-comes-into-your-home', destination: '/knowledge-hub', permanent: true },
      { source: '/the-very-sound-reasons-for-the-publication-of-pa256', destination: '/knowledge-hub', permanent: true },
      // Utility strikes specific
      { source: '/small-tools-big-consequences-the-true-cost-of-a-minor-strike', destination: '/knowledge-hub/utility-strikes-first-20-metres', permanent: true },
      { source: '/is-there-a-way-to-reduce-cable-strikes', destination: '/knowledge-hub/utility-strikes-first-20-metres', permanent: true },
      { source: '/the-danger-of-cable-strikes-and-how-to-avoid-them', destination: '/knowledge-hub/utility-strikes-first-20-metres', permanent: true },
      { source: '/cable-strikes-a-preventable-tragedy-how-to-stay-safe-when-digging', destination: '/knowledge-hub/utility-strikes-first-20-metres', permanent: true },
      { source: '/what-are-cable-strikes-and-arc-flash-accidents', destination: '/knowledge-hub/utility-strikes-first-20-metres', permanent: true },
      { source: '/striking-underground-services-when-digging-can-have-serious-repercussions', destination: '/knowledge-hub/utility-strikes-first-20-metres', permanent: true },
      { source: '/striking-underground-services-can-cause-serious-injury-and-even-be-fatal', destination: '/knowledge-hub/utility-strikes-first-20-metres', permanent: true },
      { source: '/the-shocking-figures-around-striking-underground-services-during-excavation', destination: '/knowledge-hub/utility-strikes-first-20-metres', permanent: true },
      { source: '/striking-underground-services-when-excavating-can-have-severe-implications', destination: '/knowledge-hub/utility-strikes-first-20-metres', permanent: true },
      { source: '/the-very-real-dangers-of-striking-underground-services-when-excavating', destination: '/knowledge-hub/utility-strikes-first-20-metres', permanent: true },
      { source: '/recognise-the-hidden-hazards-of-underground-services', destination: '/knowledge-hub/utility-strikes-first-20-metres', permanent: true },
      { source: '/undetected-underground-utilities-and-the-danger-they-pose-in-the-construction-industry', destination: '/knowledge-hub/utility-strikes-first-20-metres', permanent: true },
      // GSC 404 fixes
      { source: '/the-hsg47-course-that-turns-operatives-into-experts', destination: '/knowledge-hub/hsg47-explained', permanent: true },
      { source: '/if-you-need-to-locate-underground-services-you-need-an-approved-course', destination: '/courses/cable-avoidance-training', permanent: true },
      { source: '/common-challenges-of-utility-mapping', destination: '/training/utility-mapping-surveying', permanent: true },
      { source: '/how-a-utility-mapping-course-keeps-you-safe-on-site', destination: '/training/utility-mapping-surveying', permanent: true },
      { source: '/utility-mapping-training-for-proqual-level-3-qualification', destination: '/courses/level-3-certificate', permanent: true },
      { source: '/utility-surveyor-training', destination: '/training/utility-mapping-surveying', permanent: true },
      { source: '/level-5-qcf-diploma-senior-utilities-mapping-surveyor', destination: '/courses/level-5-diploma', permanent: true },
      { source: '/2026/01', destination: '/knowledge-hub', permanent: true },
      // Old category pages
      { source: '/category/hsg47-training', destination: '/knowledge-hub/hsg47-explained', permanent: true },
      { source: '/category/utility-mapping-training', destination: '/training/utility-mapping-surveying', permanent: true },
      { source: '/category/utility-detection-training', destination: '/training/cable-location-avoidance', permanent: true },
      { source: '/category/cat-genny-training', destination: '/training/cable-location-avoidance', permanent: true },
      { source: '/category/qcf-level-2-utility-avoidance-location-training', destination: '/training/cable-location-avoidance', permanent: true },
      { source: '/category/radiaodetection-cat-4-training', destination: '/courses/cat-and-genny-training', permanent: true },
      { source: '/category/cable-strikes', destination: '/knowledge-hub', permanent: true },
      { source: '/category/eusr-cable-avoidance', destination: '/courses/eusr-cat1', permanent: true },
      { source: '/category/online-training-courses', destination: '/training/cable-location-avoidance', permanent: true },
      { source: '/category/pas256-course', destination: '/courses/5-day-pas128-surveyor', permanent: true },
      { source: '/category/qcf-level-3-utility-surveyor-qualification', destination: '/courses/level-3-certificate', permanent: true },
      { source: '/category/rd8100-rd8000-training', destination: '/courses/manufacturer-locator-training', permanent: true },
      { source: '/category/vscan-training', destination: '/courses/vscan-and-transmitter-training', permanent: true },
      // SEO spider fixes
      { source: '/courses/level6diploma', destination: '/courses/level-6-diploma', permanent: true },
      { source: '/courses/utility-mapping-training-bristol', destination: '/utility-mapping-training-bristol', permanent: true },
      // Other specific fixes
      { source: '/courses/qcf-level-3-utility-mapping-surveyor', destination: '/courses/level-3-certificate', permanent: true },
      { source: '/courses/mala-hdr', destination: '/training/utility-mapping-surveying', permanent: true },
      { source: '/courses/mala-gpr-wideband', destination: '/courses/gpr-training', permanent: true },
      { source: '/courses/utility-surveyor-training-course', destination: '/courses/level-3-certificate', permanent: true },
      { source: '/courses-mala-core', destination: '/courses/gpr-training', permanent: true },
      { source: '/course-bookings', destination: '/contact', permanent: true },
      { source: '/underground-utility-location-training', destination: '/training/cable-location-avoidance', permanent: true },
      { source: '/vloc-pro-training', destination: '/courses/manufacturer-locator-training', permanent: true },
      { source: '/now-approved-by-cices', destination: '/accreditations', permanent: true },
      { source: '/wp-content/uploads/2020/05/PAS128-Client.pdf', destination: '/courses/5-day-pas128-surveyor', permanent: true },
      // Knowledge hub slug rename
      { source: '/knowledge-hub/what-is-cat-and-genny', destination: '/knowledge-hub/genny-first-methodology', permanent: true },
      // Booking redirect
      { source: '/booking', destination: '/contact', permanent: true },
      // news/page
      { source: '/news/page/24', destination: '/knowledge-hub', permanent: true },
      { source: '/news/page/31', destination: '/knowledge-hub', permanent: true },

      // === PHASE 9.1: COURSE URL VARIANTS (pre-cutover audit + LovableHTML 680-path analysis) ===
      { source: '/courses/cable-avoidance', destination: '/courses/cable-avoidance-training', permanent: true },
      { source: '/courses/gpr-survey-training', destination: '/training/utility-mapping-surveying', permanent: true },
      { source: '/courses/gpr-training-course', destination: '/courses/gpr-training', permanent: true },
      { source: '/courses/level3-certificate', destination: '/courses/level-3-certificate', permanent: true },
      { source: '/courses/mala-core', destination: '/courses/gpr-training', permanent: true },
      { source: '/courses/mala-hdr-wideband', destination: '/training/utility-mapping-surveying', permanent: true },
      { source: '/courses/eus-cat2', destination: '/courses/eusr-cat2-safe-dig', permanent: true },
      { source: '/courses/proqual-cat1', destination: '/courses/proqualcat1-training', permanent: true },
      { source: '/courses/cable-locating-specialist', destination: '/training/cable-location-avoidance', permanent: true },
      { source: '/courses/page/2', destination: '/courses', permanent: true },
      { source: '/courses/proqual-eusr', destination: '/courses/proqualcat1-training', permanent: true },
      { source: '/courses/eusrcat1plus', destination: '/courses/eusr-cat1', permanent: true },
      { source: '/courses/qcf-level-5-utility-mapping-surveyor', destination: '/courses/level-5-diploma', permanent: true },
      { source: '/courses/proqual-cat2', destination: '/courses/proqualcat2', permanent: true },

      // === PHASE 9.2: CATEGORY REDIRECTS (old WordPress /category/ structure) ===
      { source: '/category/underground-utility-surveyor-course', destination: '/training/utility-mapping-surveying', permanent: true },
      { source: '/category/mala-gpr-training', destination: '/courses/gpr-training', permanent: true },
      { source: '/category/cable-avoidance-training', destination: '/training/cable-location-avoidance', permanent: true },
      { source: '/category/vivax-training', destination: '/courses/vscan-and-transmitter-training', permanent: true },
      { source: '/category/utility-surveyor-course', destination: '/training/utility-mapping-surveying', permanent: true },
      { source: '/category/pas128-utility-surveyor-training', destination: '/courses/5-day-pas128-surveyor', permanent: true },
      { source: '/category/mala', destination: '/courses/gpr-training', permanent: true },
      { source: '/category/pa256-course', destination: '/courses/5-day-pas128-surveyor', permanent: true },
      { source: '/category/:path*', destination: '/courses', permanent: true },

      // === PHASE 9.3: TOP WORDPRESS BLOG POST REDIRECTS (highest-crawled slugs) ===
      { source: '/what-is-eusr-cat-and-genny-training-and-why-do-you-need-it', destination: '/courses/cat-and-genny-training', permanent: true },
      { source: '/cable-strikes-occur-far-too-often-and-can-be-fatal', destination: '/knowledge-hub', permanent: true },
      { source: '/what-is-a-utility-mapping-course', destination: '/training/utility-mapping-surveying', permanent: true },
      { source: '/eusr-cat-and-genny-vs-standard-cable-avoidance-training-whats-the-difference', destination: '/courses/cable-avoidance-course-comparison', permanent: true },
      { source: '/our-courses-teach-everything-you-need-to-know-about-underground-surveying', destination: '/courses', permanent: true },
      { source: '/importance-of-proper-cable-avoidance-training-and-techniques', destination: '/training/cable-location-avoidance', permanent: true },
      { source: '/our-courses-enable-you-to-obtain-your-qualification-in-cable-avoidance', destination: '/courses', permanent: true },
      { source: '/hsg47-training-from-sygma-solutions-2', destination: '/knowledge-hub/hsg47-explained', permanent: true },
      { source: '/what-does-being-a-utility-surveyor-involve', destination: '/training/utility-mapping-surveying', permanent: true },
      { source: '/cable-avoidance-tips-avoid-errors-with-expert-cat-genny-use', destination: '/training/cable-location-avoidance', permanent: true },
      { source: '/our-courses-include-limitations-of-cable-avoidance-tools', destination: '/courses', permanent: true },
      { source: '/demystifying-hsg47-breaking-down-complex-concepts', destination: '/knowledge-hub/hsg47-explained', permanent: true },
      { source: '/checking-for-underground-services-before-digging-is-essential', destination: '/training/cable-location-avoidance', permanent: true },
      { source: '/follow-best-practice-when-carrying-out-any-excavation-work', destination: '/knowledge-hub', permanent: true },
      { source: '/whatever-you-do-dont-rely-on-stats-when-excavating', destination: '/knowledge-hub', permanent: true },
      { source: '/is-cable-avoidance-training-worth-the-cost', destination: '/training/cable-location-avoidance', permanent: true },
      { source: '/cat-training-safely-trace-and-avoid-underground-utilities', destination: '/courses/cat-and-genny-training', permanent: true },
      { source: '/the-importance-of-cat-courses-and-how-they-work', destination: '/training/cable-location-avoidance', permanent: true },
      { source: '/how-can-excavators-cause-cable-strikes', destination: '/knowledge-hub', permanent: true },
      { source: '/interpreting-cat-genny-readings-like-a-pro', destination: '/courses/cat-and-genny-training', permanent: true },


      // === WS-9: REDIRECT GAPS (V8 Remediation, 10 April 2026) ===
      // 9.1: Trailing slash catch-all (Lovable had /:path+/ -> /:path+ as 301)
      { source: '/:path+/', destination: '/:path+', permanent: true },
      // 9.2: Knowledge hub slug rename (genny-first-video -> genny-first-in-practice-video)
      { source: '/knowledge-hub/genny-first-video', destination: '/knowledge-hub/genny-first-in-practice-video', permanent: true },
      // 9.3: Duplicate design-your-programme routes (dirs already removed, redirects needed)
      { source: '/courses/design-your-programme', destination: '/bespoke-training', permanent: true },
      { source: '/courses/designyourprogramme', destination: '/bespoke-training', permanent: true },
      // 9.4: Individual case study redirects (pages merge into knowledge hub per Pete's decision)
      { source: '/case-studies/kier-group', destination: '/knowledge-hub/kier-group-case-study', permanent: true },
      { source: '/case-studies/qts-group', destination: '/knowledge-hub/qts-group-case-study', permanent: true },
      { source: '/case-studies/morgan-sindall', destination: '/knowledge-hub/morgan-sindall-case-study', permanent: true },
      { source: '/case-studies/severn-trent-water', destination: '/knowledge-hub/severn-trent-water-case-study', permanent: true },
      { source: '/courses/case-studies/:path*', destination: '/knowledge-hub', permanent: true },
      // 9.5: Sub-path catch-alls for prefixes excluded from the single-level catch-all below.
      // These use negative lookaheads to avoid intercepting real Next.js pages (real slugs listed in the exclusion).
      // Any unlisted sub-path under these prefixes would otherwise 404; now it redirects cleanly.
      { source: '/case-studies/:path*', destination: '/knowledge-hub', permanent: true },
      { source: '/mala-gpr/:path*', destination: '/courses/gpr-training', permanent: true },
      { source: '/training/:path((?!cable-location-avoidance|utility-mapping-surveying).+)', destination: '/courses', permanent: true },
      { source: '/locations/:path((?!manchester|birmingham|london|bristol).+)', destination: '/locations', permanent: true },

      // === PHASE 9.6: CATCH-ALL FOR REMAINING OLD WORDPRESS BLOG POSTS (MUST BE LAST) ===
      // NOTE: allow-list must include IndexNow verification key filename (93myyfw...). Anything else served from /public at root also needs an entry here.
      { source: '/:slug((?!courses|training|knowledge-hub|locations|case-studies|about|contact|pricing|osca|bespoke-training|accreditations|privacy-policy|thank-you|sitemap|design|utility-mapping|cable-avoidance|api|_next|images|favicon|logo|icon|manifest|robots|downloads|category|services|mala-gpr|93myyfwu1byms8f99y6pj8xt57sx5rxu).+)', destination: '/knowledge-hub', permanent: true },
    ];
  },
};

export default nextConfig;