import { NextResponse } from 'next/server';
import type { NextRequest } from 'next/server';

/**
 * Old WordPress blog-post slugs that are GONE (not renamed to a new URL).
 * Returning 410 Gone instead of 308-redirecting them to /knowledge-hub signals
 * Google more aggressively to drop these from the index. Source: GSC export
 * 2026-05-13 -- specifically the "Crawled - currently not indexed" bucket plus
 * the SEO-spam-style WordPress posts from the "Page with redirect" bucket that
 * have no current equivalent.
 *
 * Process for adding new entries:
 *   1. URL must have NO equivalent on the current site (don't 410 a renamed page)
 *   2. URL was clearly SEO-spam-era content (long descriptive slug, generic topic)
 *   3. Verify the URL isn't in next.config.mjs redirects pointing to a real page
 *
 * Lookup is O(1) Set membership; matcher below excludes static assets so this
 * adds essentially zero overhead per request.
 */
const GONE_PATHS = new Set<string>([
  // From GSC "Crawled - currently not indexed" (66) -- the thin-content ones
  '/protect-lives-and-careers-with-cable-avoidance-skills',
  '/far-too-many-contractors-are-failing-to-check-for-cables-before-excavating',
  '/what-does-being-a-utility-surveyor-involve',
  '/cable-avoidance-training-is-critical-for-contractors-undertaking-groundwork',
  '/some-of-the-things-you-will-learn-on-sygma-solutions-training-courses',
  '/where-can-i-find-the-best-cable-avoidance-tools',
  '/shape-your-career-in-the-utility-service-sector-with-eusr-hsg47-training',
  '/the-very-sound-reasons-for-the-publication-of-pa256',
  '/striking-an-underground-utility-can-be-life-threatening',
  '/2013-december-free-mala-course-a-huge-success',
  '/the-multiple-issues-surrounding-location-of-underground-services',
  '/whatever-you-do-dont-rely-on-stats-when-excavating',
  '/2018-public-cat-and-genny-training',
  '/shocking-statistics-concerning-safety-when-carrying-out-excavations',
  '/vscan-training-from-sygma-solutions',
  '/sygma-solutions-provides-complete-training-in-the-use-of-the-cat-and-genny',
  '/our-traditional-courses-now-available-online',
  '/cable-avoidance-training-is-essential-if-you-need-to-locate-underground-services',
  '/any-kind-of-excavation-work-can-be-dangerous',
  '/everything-that-you-need-to-know-to-apply-for-a-cscs-utility-surveyor-card',
  '/the-importance-of-training-for-utility-detection-equipment-and-surveying',
  '/get-cable-avoidance-and-hsg47-training-by-sygma-solutions',
  '/training-in-the-use-of-tools-for-detecting-underground-services-is-essential',
  '/how-to-achieve-success-with-cable-avoidance',
  '/proper-training-in-the-use-of-the-cat-and-genny-is-essential',
  '/why-sygma-solutions-cat-and-genny-training-is-critical-knowledge',
  '/cscs-card-opportunities-in-the-construction-industry',
  '/some-things-to-consider-when-investing-in-cable-avoidance-tools',
  '/thorough-training-is-needed-in-order-to-fully-understand-the-cat-and-genny',
  '/striking-underground-services-when-digging-can-be-fatal',
  '/hsg47-and-remote-utility-detection-shaping-the-digital-age-practice',
  '/maintaining-the-accuracy-of-your-cat-and-genny-gear',
  '/our-online-cable-avoidance-training-is-ideal',
  '/pros-and-cons-of-a-career-in-cable-avoidance',
  '/repeated-near-misses-on-uk-sites-and-what-eusr-training-would-have-caught-earlier',
  '/it-is-essential-to-carry-out-a-survey-before-undertaking-any-excavation',
  '/our-courses-include-limitations-of-cable-avoidance-tools',

  // From GSC "Page with redirect" (416) -- generic SEO-spam blog posts that
  // were redirecting to /knowledge-hub. Confirmed obsolete (long descriptive
  // slugs, generic topics, no current equivalent page).
  '/striking-underground-services-when-digging-can-have-serious-repercussions',
  '/striking-underground-services-can-cause-serious-injury-and-even-be-fatal',
  '/the-shocking-figures-around-striking-underground-services-during-excavation',
  '/striking-underground-services-when-excavating-can-have-severe-implications',
  '/the-very-real-dangers-of-striking-underground-services-when-excavating',
  '/recognise-the-hidden-hazards-of-underground-services',
  '/undetected-underground-utilities-and-the-danger-they-pose-in-the-construction-industry',
  '/underground-services-can-be-anywhere-even-in-places-you-might-not-expect',
  '/underground-services-can-literally-be-anywhere',
  '/training-in-the-avoidance-of-underground-services-is-essential',
  '/the-importance-of-training-for-utility-detection-equipment-and-surveying',
  '/do-you-know-exactly-where-the-electricity-cable-comes-into-your-home',
  '/small-tools-big-consequences-the-true-cost-of-a-minor-strike',
  '/is-there-a-way-to-reduce-cable-strikes',
  '/the-danger-of-cable-strikes-and-how-to-avoid-them',
  '/cable-strikes-a-preventable-tragedy-how-to-stay-safe-when-digging',
  '/what-are-cable-strikes-and-arc-flash-accidents',
  '/why-having-a-permit-doesnt-mean-youre-hsg47-compliant',
  '/hsg47-is-a-guide-issued-by-the-hse-for-those-involved-in-any-sort-of-excavation',
  '/how-do-cable-locators-work-key-principles-of-buried-utility-detection',
  '/when-using-cable-avoidance-tools-you-need-to-understand-their-limitations',
  '/what-is-the-right-cable-avoidance-tool-cat-for-your-needs',
  '/expert-qa-get-your-cat-genny-questions-answered',
  '/if-undertaking-excavation-work-it-is-best-practice-to-use-line-search-before-u-dig',
  '/cat-genny-training-what-is-it-what-it-involves',
  '/a-step-by-step-guide-for-aspiring-utility-surveyors-in-the-uk',
  '/how-cat-and-genny-training-enhances-site-safety',
  '/locating-underground-services-is-essential-before-any-excavation',
  '/cutting-the-cord-a-beginners-guide-to-cable-avoidance',
  '/cat-and-genny-training-the-basics',
  '/how-does-the-radiodetection-rd8100-tool-work',
  '/understanding-the-radiodetection-rd8100-a-guide-to-utility-locating',
  '/it-is-essential-to-carry-out-a-survey-before-undertaking-any-excavation-work',
  '/before-digging-on-a-construction-project-it-is-essential-to-carry-out-a-survey',
  '/locating-underground-services-what-you-need-to-know',
  '/excavation-safety-a-crash-course',
  '/how-to-choose-the-right-cable-avoidance-tool',
  '/how-to-reduce-the-risks-of-cable-avoidance',
  '/cable-avoidance-101-a-beginners-guide-to-safe-digging',
  '/hsg47-training-safely-detect-and-avoid-underground-services',
  '/hsg47-what-you-need-to-know-about-excavations',
  '/hsg47-course-practical-skills-for-underground-safety',
  '/do-you-need-eusr-hsg47',
  '/hsg47-training-whats-it-all-about',
  '/integrating-hsg47-training-with-pas-128-standards',
  '/overcoming-challenges-in-hsg47-training',
  '/why-hsg47-training-is-your-secret-weapon-for-safer-utility-work',
  '/hsg47-and-the-rise-of-mixed-utility-corridors-why-your-old-work-habits-dont-apply',
  '/understanding-the-hsg47-utility-mapping-certification-process',
  '/eusr-hsg47-training-from-sygma-solutions',
  '/eusr-hsg47-essentials-every-utility-worker-needs-to-know',
  '/operatives-who-need-to-locate-underground-services-need-hsg47-training',
  '/what-are-the-pressing-questions-about-hsg47',
  '/understanding-hsg-47-an-overview',
  '/our-hsg47-training-teaches-you-everything-you-need-to-know',
  '/the-hsg47-certification-you-should-not-ignore-protect-yourselves',
  '/the-hidden-costs-of-skipping-hsg47-training-real-world-lessons-from-cable-strikes',
  '/advice-from-the-hse-on-avoiding-dangers-from-excavation-works',
  '/understanding-hsg-47-a-guide-for-utility-detection-professionals',
  '/eusr-cat-and-genny-training-from-sygma-solutions',
  '/eusr-certification-your-guide-to-utility-safety-training',
  '/eusr-cat-and-genny-training-that-sets-utility-pros-apart',
  '/eusr-utility-location-training-cat-genny',
  '/why-is-eusr-the-best-training-program-for-cable-avoidance',
  '/understanding-the-eusr-certification-process-for-cat-and-genny-operators',
  '/stay-compliant-safe-cat-genny-certification-explained',
  '/our-utility-mapping-course-teaches-everything-you-need-to-know',
  '/to-become-a-utility-surveyor-you-need-top-class-training',
  '/utility-mapping-101-understanding-the-basics',
  '/digging-smart-why-utility-mapping-training-is-essential',
  '/utility-mapping-isnt-optional-anymore-heres-why',
  '/what-is-cscs-utility-mapping',
  '/our-underground-surveyor-courses-teach-everything-you-need-to-know',
  '/utility-coding-explained-a-sygma-solutions-guide',
  '/utility-location-training-hands-on-real-world-skills',
  '/new-utility-mapping-training-online',
  '/understanding-the-red-lines-a-beginners-guide-to-reading-utility-stats-plans',
  '/the-proqual-level-2-award-in-utility-avoidance',
  '/level-5-qcf-diploma-senior-utilities-mapping-surveyor-qualification',
  '/achieve-your-level-5-qcf-diploma-senior-utilities-surveyor-qualification',
  '/what-you-need-to-know-in-order-to-become-a-level-5-utility-surveyor',
  '/proqual-qcf-level-3-utility-surveyor-training-is-now-available-online',
  '/ground-penetrating-radar-gpr-training',
  '/what-you-need-to-know-about-gpr-locators',
  '/mala-easy-locator-gets-easier-to-hire',
  '/we-are-the-sole-uk-distributor-for-the-mala-easy-locator-hdr',
  '/sygma-solutions-can-provide-you-with-mala-easy-locator-gpr-machines',
  '/what-you-need-to-know-about-the-use-of-the-rd8100-cable-locator',
  '/training-in-the-use-of-the-rd8100-from-sygma-solutions',
  '/what-utility-strikes-reveal-about-teams-that-havent-had-radiodetection-training',
  '/the-key-to-utility-detection-radiodetection-training-that-works',
  '/sygma-solutions-can-provide-training-in-the-use-of-the-c-scope-tools',
  '/cat-4-and-genny-4-training-from-sygma-solutions',
  '/an-overview-of-the-sygma-solutions-cat-and-genny-course',
  '/who-needs-cat-genny-training-and-what-can-they-learn',
  '/reasons-for-using-the-cat-genny-for-location-of-buried-services',
  '/learn-the-basics-of-cat-and-genny-training-online',
  '/cat-and-genny-training-from-sygma-solutions',
  '/sygma-solutions-cat-and-genny-training-for-safer-operations',
  '/sygma-solutions-leading-the-way-in-cat-and-genny-training',
  '/maximising-the-potential-of-cat-and-genny-tools',
  '/who-needs-cat-and-genny-training-guide-for-utility-professionals',
  '/choosing-the-right-cat-and-genny-mode-for-every-job',
  '/online-cat-genny-training-prevent-costly-utility-strikes',
  '/new-online-live-cat-genny-training',
  '/hidden-wins-of-the-cat-genny-course-no-one-talks-about',
  '/how-weather-ground-type-and-site-conditions-distort-cat-genny-performance',
  '/navigating-high-frequency-signal-noise-in-urban-locating',
  '/why-your-cat-data-is-the-new-site-blueprint',
  '/the-data-trail-in-2026-why-your-cat4-memory-log-is-now-a-legal-requirement',
  '/the-quiet-line-challenge-locating-abandoned-or-non-live-utilities',
  '/why-higher-isnt-always-better-in-2026-urban-locating',
  '/advanced-techniques-for-identifying-ghost-signals-in-cable-avoidance',
  '/cable-avoidance-training-is-critical-for-contractors-undertaking-groundwork',
  '/cable-avoidance-training-for-safe-digging-and-excavation-work',
  '/our-training-will-enable-a-qualification-in-cable-avoidance',
  '/reduce-risk-stay-compliant-with-online-cable-avoidance-training',
  '/cable-avoidance-training-is-essential-for-those-who-need-to-locate-buried-services',
  '/cable-avoidance-training-from-sygma-solutions',
  '/enroll-in-cable-avoidance-training-to-prevent-utility-strikes',
  '/5-things-learn-in-your-cable-avoidance-training-course',
  '/cable-strike-avoidance-training-from-sygma-solutions',
  '/master-cable-avoidance-with-sygmas-expert-training',
  '/what-most-people-miss-about-cable-avoidance-training',
  '/why-practical-experience-matters-more-than-manuals-in-cable-avoidance-training',
  '/the-evolution-of-cable-avoidance-tools',
  '/cable-avoidance-training-advice',
  '/cable-avoidance-training-for-network-rail',
  '/cable-avoidance-training-manchester-city-centre',
  '/common-challenges-in-cable-avoidance',
  '/strategies-and-best-practices-for-cable-avoidance',
  '/why-accurate-cable-location-is-the-first-step-to-a-safe-worksite',
  '/our-cable-avoidance-training-covers-the-limitations-of-the-equipment-used',
  '/dont-guess-detect-why-cable-avoidance-training-matters',
  '/why-you-need-to-undertake-a-utility-avoidance-training-course',
  '/important-rules-to-follow-for-cable-avoidance',
  '/learn-to-safely-use-cat-and-genny-tools-for-excavation-projects',
  '/catscan-training-for-cable-avoidance-is-critical',
  '/troubleshooting-common-issues-with-cat-tools',
  '/sygma-solutions-is-the-leading-cable-avoidance-training-company-in-the-uk',
  '/the-foremost-uk-provider-of-training-for-the-location-of-underground-services',
  '/sygma-solutions-specialists-in-the-training-of-underground-services-location',
  '/our-courses-are-perfect-to-enable-you-to-gain-the-qualifications-you-need',
  '/2013-november-sygma-solutions-ltd-relocates',
  '/striking-underground-services-when-digging-can-be-fatal',
  '/stop-strikes-before-they-start-with-utility-detection',
  '/five-warning-signs-youre-about-to-hit-a-cable-and-how-to-avoid-it',
  '/what-is-excavation-safety',
  '/health-safety-in-the-construction-industry',
  '/it-is-always-necessary-to-obtain-plans-from-utilities-before-doing-any-form-of-excavation',
  '/why-a-site-survey-is-essential-before-carrying-out-any-excavation-work',
  '/the-hsg47-course-that-turns-operatives-into-experts',
  '/if-you-need-to-locate-underground-services-you-need-an-approved-course',
  '/common-challenges-of-utility-mapping',
  '/how-a-utility-mapping-course-keeps-you-safe-on-site',
  '/utility-mapping-training-for-proqual-level-3-qualification',
  '/utility-surveyor-training',
  '/level-5-qcf-diploma-senior-utilities-mapping-surveyor',
  '/what-is-eusr-cat-and-genny-training-and-why-do-you-need-it',
  '/cable-strikes-occur-far-too-often-and-can-be-fatal',
  '/what-is-a-utility-mapping-course',
  '/eusr-cat-and-genny-vs-standard-cable-avoidance-training-whats-the-difference',
  '/our-courses-teach-everything-you-need-to-know-about-underground-surveying',
  '/importance-of-proper-cable-avoidance-training-and-techniques',
  '/our-courses-enable-you-to-obtain-your-qualification-in-cable-avoidance',
  '/hsg47-training-from-sygma-solutions-2',
  '/cable-avoidance-tips-avoid-errors-with-expert-cat-genny-use',
  '/demystifying-hsg47-breaking-down-complex-concepts',
  '/checking-for-underground-services-before-digging-is-essential',
  '/follow-best-practice-when-carrying-out-any-excavation-work',
  '/is-cable-avoidance-training-worth-the-cost',
  '/cat-training-safely-trace-and-avoid-underground-utilities',
  '/the-importance-of-cat-courses-and-how-they-work',
  '/how-can-excavators-cause-cable-strikes',
  '/interpreting-cat-genny-readings-like-a-pro',
  '/role-of-cat-training-in-preventing-cable-strikes',
]);

export function middleware(request: NextRequest) {
  const pathname = request.nextUrl.pathname;

  // 410 Gone for old WordPress blog posts that are confirmed deleted.
  // Returning 410 (instead of 308 -> /knowledge-hub) signals Google to drop
  // these from the index much faster than a redirect would.
  //
  // Note: trailing-slash variants (/foo/) hit Next.js's built-in trailing-
  // slash redirect FIRST and arrive here without the slash. So we only need
  // the no-trailing-slash form in GONE_PATHS.
  if (GONE_PATHS.has(pathname)) {
    return new NextResponse(
      `<!DOCTYPE html><html><head><title>410 Gone</title><meta name="robots" content="noindex"></head><body><h1>410 Gone</h1><p>This page no longer exists. Please visit our <a href="/knowledge-hub">Knowledge Hub</a> for current articles.</p></body></html>`,
      {
        status: 410,
        headers: {
          'Content-Type': 'text/html; charset=utf-8',
          'X-Robots-Tag': 'noindex',
        },
      },
    );
  }

  return NextResponse.next();
}

export const config = {
  // Skip static assets so the middleware doesn't run on every JS/CSS/image
  // request -- only on actual page paths.
  matcher: ['/((?!_next/static|_next/image|favicon.ico|api/|images/|assets/).*)'],
};
